CREATE TABLE IF NOT EXISTS usuario (
  id SERIAL PRIMARY KEY,
  firebase_uid VARCHAR(128) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  rol_id INTEGER NOT NULL DEFAULT 1,
  foto_perfil_url TEXT,
  creado_en TIMESTAMP DEFAULT NOW(),
  CONSTRAINT fk_usuario_rol
    FOREIGN KEY (rol_id)
    REFERENCES rol(id)
    ON DELETE RESTRICT
);
